version: '3.8'
services:
  phoenixd:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "9740:9740"
    volumes:
      - ./phoenix_data:/root/.phoenix
    command: ./phoenixd
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: earthly
      POSTGRES_PASSWORD: earthlypassword
      POSTGRES_DB: earthly_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
